<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'ExternalLinterUtils' => 'lint/ExternalLinterUtils.php',
    'FBSourceGoogleJavaFormatLinter' => 'lint/linter/FBSourceGoogleJavaFormatLinter.php',
    'FormatterUtils' => 'lint/FormatterUtils.php',
    'WhatsAppAndroidKotlinFormatLinter' => 'lint/linter/WhatsAppAndroidKotlinFormatLinter.php',
    'WhatsAppAndroidLintEngine' => 'lint/WhatsAppAndroidLintEngine.php',
    'WhatsAppAndroidPythonFormatLinter' => 'lint/linter/WhatsAppAndroidPythonFormatLinter.php',
    'WhatsAppAndroidSimpleLintEngine' => 'lint/WhatsAppAndroidSimpleLintEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'ExternalLinterUtils' => 'Phobject',
    'FBSourceGoogleJavaFormatLinter' => 'ArcanistFutureLinter',
    'FormatterUtils' => 'Phobject',
    'WhatsAppAndroidKotlinFormatLinter' => 'ArcanistFutureLinter',
    'WhatsAppAndroidLintEngine' => 'ArcanistLintEngine',
    'WhatsAppAndroidPythonFormatLinter' => 'ArcanistFutureLinter',
    'WhatsAppAndroidSimpleLintEngine' => 'WhatsAppAndroidLintEngine',
  ),
));
